export const ROOM_NOT_FOUND = "ROOM_NOT_FOUND"
export const USER_NOT_FOUND = "USER_NOT_FOUND"
export const SONG_NOT_FOUND = "SONG_NOT_FOUND"
export const INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS";
export const INVALID_JSON = "INVALID_JSON";
export const UNKNOWN_SERVER_ERROR = "UNKNOWN_SERVER_ERROR";
